### ISSUE TITLE
Won't install on Windows 8.1

### ISSUE THREAD

**Issue by semiaddict** [atom/buffer-offset-index#1]
Hello,

I am trying to install *buffer-offset-index* on a Windows 8.1 machine, but I keep getting the following error messages:

    > buffer-offset-index@0.0.1 install ***\node_modules\buffer-offset-index
    > node-gyp rebuild
    
    
    ***\node_modules\buffer-offset-index>if not defined npm_config_node_gyp (node "C:\Users\***\AppData\Roaming\nvm\v6.9.1\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
    Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
      binding.cc
      buffer_offset_index.cc
      win_delay_load_hook.cc
    ..\src\buffer_offset_index.cc(67): warning C4267: 'argument' : conversion from 'size_t' to 'unsigned int', possible loss of data [***\node_modules\buffer-offse t-index\build\buffer_offset_index.vcxproj]
    ..\src\buffer_offset_index.cc(78): warning C4267: 'argument' : conversion from 'size_t' to 'unsigned int', possible loss of data [***\node_modules\buffer-offse t-index\build\buffer_offset_index.vcxproj]
    ..\src\buffer_offset_index.cc(87): warning C4267: 'argument' : conversion from 'size_t' to 'unsigned int', possible loss of data [***\node_modules\buffer-offse t-index\build\buffer_offset_index.vcxproj]
    ..\src\buffer_offset_index.cc(94): error C2065: 'UINT32_MAX' : undeclared identifier [***\node_modules\buffer-offset-index\build\buffer_offset_index.vcxproj]
    ..\src\buffer_offset_index.cc(97): error C3536: 'rng': cannot be used before it is initialized [***\node_modules\buffer-offset-index\build\buffer_offset_index. vcxproj]
    ..\src\buffer_offset_index.cc(97): error C2064: term does not evaluate to a function taking 1 arguments [***\node_modules\buffer-offset-index\build\buffer_offs et_index.vcxproj]
    ..\src\buffer_offset_index.cc(102): error C3536: 'rng': cannot be used before it is initialized [***\node_modules\buffer-offset-index\build\buffer_offset_index .vcxproj]
    ..\src\buffer_offset_index.cc(102): error C2064: term does not evaluate to a function taking 1 arguments [***\node_modules\buffer-offset-index\build\buffer_off set_index.vcxproj]
    ..\src\buffer_offset_index.cc(201): error C2065: 'UINT32_MAX' : undeclared identifier [***\node_modules\buffer-offset-index\build\buffer_offset_index.vcxproj]
    ..\src\buffer_offset_index.cc(202): error C2065: 'UINT32_MAX' : undeclared identifier [***\node_modules\buffer-offset-index\build\buffer_offset_index.vcxproj]
    ..\src\buffer_offset_index.cc(203): error C3536: 'left_child_priority': cannot be used before it is initialized [***\node_modules\buffer-offset-index\build\buf fer_offset_index.vcxproj]
    ..\src\buffer_offset_index.cc(203): error C3536: 'right_child_priority': cannot be used before it is initialized [***\node_modules\buffer-offset-index\build\bu ffer_offset_index.vcxproj]
    ..\src\buffer_offset_index.cc(203): warning C4018: '<' : signed/unsigned mismatch [***\node_modules\buffer-offset-index\build\buffer_offset_index.vcxproj]
    ..\src\buffer_offset_index.cc(207): error C3536: 'right_child_priority': cannot be used before it is initialized [***\node_modules\buffer-offset-index\build\bu ffer_offset_index.vcxproj]
    ..\src\buffer_offset_index.cc(207): warning C4018: '<' : signed/unsigned mismatch [***\node_modules\buffer-offset-index\build\buffer_offset_index.vcxproj]
    ..\src\buffer_offset_index.cc(257): error C2065: 'UINT32_MAX' : undeclared identifier [***\node_modules\buffer-offset-index\build\buffer_offset_index.vcxproj]
    ..\src\buffer_offset_index.cc(258): error C3536: 'rng': cannot be used before it is initialized [***\node_modules\buffer-offset-index\build\buffer_offset_index .vcxproj]
    ..\src\buffer_offset_index.cc(258): error C2064: term does not evaluate to a function taking 1 arguments [***\node_modules\buffer-offset-index\build\buffer_off set_index.vcxproj]
    ..\src\binding.cc(118): warning C4267: 'argument' : conversion from 'size_t' to 'uint32_t', possible loss of data [***\node_modules\buffer-offset-index\build\b uffer_offset_index.vcxproj]
    gyp ERR! build error
    gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (C:\Users\***\AppData\Roaming\nvm\v6.9.1\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
    gyp ERR! stack     at emitTwo (events.js:106:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
    gyp ERR! System Windows_NT 6.3.9600
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\***\\AppData\\Roaming\\nvm\\v6.9.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd ***\node_modules\buffer-offset-index
    gyp ERR! node -v v6.9.1
    gyp ERR! node-gyp -v v3.4.0
    gyp ERR! not ok
    npm ERR! Windows_NT 6.3.9600
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "buffer-offset-index"
    npm ERR! node v6.9.1
    npm ERR! npm  v3.10.8
    npm ERR! code ELIFECYCLE
    
    npm ERR! buffer-offset-index@0.0.1 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the buffer-offset-index@0.0.1 install script 'node-gyp rebuild'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the buffer-offset-index package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs buffer-offset-index
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls buffer-offset-index
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     ***\npm-debug.log

I have tried several versions of node (from 0.12.7 to 6.9.1) via nvm, but nothing changed.

Do you have an idea of why this is happening ?

Thank you in advance,

Oussama

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
